{{- if .Values.backrest.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    pg-cluster: {{ .Values.name | quote }}
    vendor: crunchydata
  name: {{ .Values.name }}-{{- if .Values.username }}{{ .Values.username }}{{- else }}{{ .Values.name }}{{- end }}-backrest-repo-config
  namespace: {{ .Release.Namespace }}
data:
  aws-s3-key: {{ .Values.backrest.s3Key | b64enc | quote }}
  aws-s3-key-secret: {{ .Values.backrest.s3Secret | b64enc | quote }}
{{- end -}}
